config/routes.rb
MyGists::Application.routes.draw do
  resources :gists

end

app/models/gist.rb
class Gist < ActiveRecord::Base

def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
else
   scoped
 end
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.search(params[:search]).paginate(page: params[:page], per_page: 10).order('created_at DESC')

      respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gists/_gist.html.erb
<tr>
        <td>
        	<% my_snippet = gist.snippet[0..50] %>
		<%= raw Pygments.highlight(my_snippet, lexer: gist.lang) %>
        	</td>
        <td><%= gist.lang %></td>
        <td>
        	<% 
					my_string = gist.description[0..50]
					if(my_string.length > 49)
						 my_string += "..."
						end
				%>
				<%= my_string %>
        </td>
        <td><%= link_to image_tag("http://s28.postimg.org/cp6fblk7t/document_search.png", {:alt=>"Show", :title=>"Show"}) , gist, :class => 'showGist'  %></td>
        <td><%= link_to image_tag("http://s28.postimg.org/hy1g9h2mx/document_edit.png", {:alt=>"Edit", :title=>"Edit"}) , edit_gist_path(gist), :class => 'editGist' %></td>
        <td><%= link_to image_tag("http://s28.postimg.org/wiij4axll/document_delete.png", {:alt=>"Delete", :title=>"Delete"}) , gist, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'deleteGist' %></td>
      </tr>

app/views/gists/edit.html.erb
<h1>Editing gist</h1>

<%= render 'form' %>

<%= link_to 'Show', @gist %> |
<%= link_to 'Back', gists_path %>

app/views/gists/index.html.erb
<h1>Listing gists</h1>
<%= link_to image_tag("http://s30.postimg.org/v1cu28ml9/document_add.png", {:alt=>"Add", :title=>"Add"}), new_gist_path %>

<table>
  <thead>
    <tr>
      <th>Snippet</th>
      <th>Lang</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="my-gists">
    <%= render @gists %>
</tbody>
</table>

<div id="infinite-scrolling">
<%= will_paginate @gists, renderer: BootstrapPagination::Rails%>
</div>
<br>

app/views/gists/index.js.erb
$('#my-gists').append('<%= j render @gists %>');
$('.pagination').replaceWith('<%= j will_paginate @gists, renderer: BootstrapPagination::Rails %>');
isActive = false;

app/views/gists/new.html.erb
<h1>New gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path %>

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Lang:</strong>
  <%= @gist.lang %>
</p>
<p>
  <strong>Snippet:</strong>
</p>
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
<p>
  <strong>Description:</strong>
  <%= @gist.description %>
</p>
<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<ul class="nav nav-tabs">
		<li><%= link_to "Strona główna", "http://pk-gists.herokuapp.com" %></li>
		<li><%= link_to "Projekt na Github.com", "https://github.com/pkurnyta/my_gists" %></li>
	</ul>
<div class="pull-right" style="padding: 3px;">
<%= form_tag gists_path, :method => 'get',:class =>"form-search", :id => "gists_search" do %>
<%= text_field_tag :search, params[:search], :class => 'input-medium search-query'%>
<%= submit_tag "Szukaj", :name => nil, :class => 'btn btn-primary active' %>
<% end %>
</div>

<%= yield %>
</div>
</body>
</html>